// Generated by gencpp from file leap_client/FingerInfo.msg
// DO NOT EDIT!


#ifndef LEAP_CLIENT_MESSAGE_FINGERINFO_H
#define LEAP_CLIENT_MESSAGE_FINGERINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace leap_client
{
template <class ContainerAllocator>
struct FingerInfo_
{
  typedef FingerInfo_<ContainerAllocator> Type;

  FingerInfo_()
    : header()
    , hand_id(0)
    , id(0)
    , time_visible(0.0)
    , tip_position()
    , tip_velocity()
    , pointing_direction()
    , stabilized_tip_position()  {
    }
  FingerInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hand_id(0)
    , id(0)
    , time_visible(0.0)
    , tip_position(_alloc)
    , tip_velocity(_alloc)
    , pointing_direction(_alloc)
    , stabilized_tip_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _hand_id_type;
  _hand_id_type hand_id;

   typedef int32_t _id_type;
  _id_type id;

   typedef float _time_visible_type;
  _time_visible_type time_visible;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _tip_position_type;
  _tip_position_type tip_position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _tip_velocity_type;
  _tip_velocity_type tip_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pointing_direction_type;
  _pointing_direction_type pointing_direction;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _stabilized_tip_position_type;
  _stabilized_tip_position_type stabilized_tip_position;




  typedef boost::shared_ptr< ::leap_client::FingerInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leap_client::FingerInfo_<ContainerAllocator> const> ConstPtr;

}; // struct FingerInfo_

typedef ::leap_client::FingerInfo_<std::allocator<void> > FingerInfo;

typedef boost::shared_ptr< ::leap_client::FingerInfo > FingerInfoPtr;
typedef boost::shared_ptr< ::leap_client::FingerInfo const> FingerInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leap_client::FingerInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leap_client::FingerInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace leap_client

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'leap_client': ['/home/dzhi/catkin_ws/src/leap_client/msg', '/home/dzhi/catkin_ws/src/leap_client/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::leap_client::FingerInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leap_client::FingerInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_client::FingerInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leap_client::FingerInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_client::FingerInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leap_client::FingerInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leap_client::FingerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c03d82510bf929e1b9514a3af01d675b";
  }

  static const char* value(const ::leap_client::FingerInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc03d82510bf929e1ULL;
  static const uint64_t static_value2 = 0xb9514a3af01d675bULL;
};

template<class ContainerAllocator>
struct DataType< ::leap_client::FingerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leap_client/FingerInfo";
  }

  static const char* value(const ::leap_client::FingerInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leap_client::FingerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int32 hand_id\n\
int32 id\n\
float32 time_visible\n\
geometry_msgs/Point tip_position\n\
geometry_msgs/Vector3 tip_velocity\n\
geometry_msgs/Vector3 pointing_direction\n\
geometry_msgs/Point stabilized_tip_position\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::leap_client::FingerInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leap_client::FingerInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hand_id);
      stream.next(m.id);
      stream.next(m.time_visible);
      stream.next(m.tip_position);
      stream.next(m.tip_velocity);
      stream.next(m.pointing_direction);
      stream.next(m.stabilized_tip_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingerInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leap_client::FingerInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leap_client::FingerInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hand_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hand_id);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "time_visible: ";
    Printer<float>::stream(s, indent + "  ", v.time_visible);
    s << indent << "tip_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.tip_position);
    s << indent << "tip_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.tip_velocity);
    s << indent << "pointing_direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pointing_direction);
    s << indent << "stabilized_tip_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.stabilized_tip_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEAP_CLIENT_MESSAGE_FINGERINFO_H
